/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppEntry = IDL.Record({
  'id' : IDL.Text,
  'signUpBonus' : IDL.Nat,
  'referralLink' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'logoUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'minWithdrawal' : IDL.Nat,
  'downloadCount' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteSettings = IDL.Record({
  'siteTitle' : IDL.Text,
  'tagline' : IDL.Text,
  'footerNote' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addApp' : IDL.Func([AppEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteApp' : IDL.Func([IDL.Text], [], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllApps' : IDL.Func([], [IDL.Vec(AppEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedApps' : IDL.Func([], [IDL.Vec(AppEntry)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminPhone' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAdminPhone' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApp' : IDL.Func([AppEntry], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppEntry = IDL.Record({
    'id' : IDL.Text,
    'signUpBonus' : IDL.Nat,
    'referralLink' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'logoUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'minWithdrawal' : IDL.Nat,
    'downloadCount' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteSettings = IDL.Record({
    'siteTitle' : IDL.Text,
    'tagline' : IDL.Text,
    'footerNote' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addApp' : IDL.Func([AppEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteApp' : IDL.Func([IDL.Text], [], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllApps' : IDL.Func([], [IDL.Vec(AppEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedApps' : IDL.Func([], [IDL.Vec(AppEntry)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminPhone' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAdminPhone' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApp' : IDL.Func([AppEntry], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };