/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppEntry {
  'id' : string,
  'signUpBonus' : bigint,
  'referralLink' : string,
  'sortOrder' : bigint,
  'name' : string,
  'logoUrl' : string,
  'isFeatured' : boolean,
  'minWithdrawal' : bigint,
  'downloadCount' : string,
}
export interface SiteSettings {
  'siteTitle' : string,
  'tagline' : string,
  'footerNote' : string,
  'youtubeLink' : string,
  'telegramLink' : string,
  'instagramLink' : string,
  'facebookLink' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addApp' : ActorMethod<[AppEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteApp' : ActorMethod<[string], undefined>,
  'generateOTP' : ActorMethod<[string], string>,
  'getAllApps' : ActorMethod<[], Array<AppEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedApps' : ActorMethod<[], Array<AppEntry>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminPhone' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerAdminPhone' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApp' : ActorMethod<[AppEntry], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];